apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: '2024-04-08T14:40:05Z'
  name: hld-dinner-hpa
  namespace: default
  resourceVersion: '1134809'
  uid: 5cc511c3-b868-4b47-b0ce-ee259eeee22b
spec:
  behavior:
    scaleDown:
      policies:
        - periodSeconds: 15
          type: Percent
          value: 100
      selectPolicy: Max
      stabilizationWindowSeconds: 600
    scaleUp:
      policies:
        - periodSeconds: 5
          type: Pods
          value: 4
        - periodSeconds: 5
          type: Percent
          value: 1000
      selectPolicy: Max
      stabilizationWindowSeconds: 0
  maxReplicas: 50
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 50
          type: Utilization
      type: Resource
  minReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hls-dinner
status:
  conditions:
    - lastTransitionTime: '2024-04-08T14:40:20Z'
      message: >-
        recent recommendations were higher than current one, applying the
        highest recent recommendation
      reason: ScaleDownStabilized
      status: 'True'
      type: AbleToScale
    - lastTransitionTime: '2024-04-13T09:55:45Z'
      message: >-
        the HPA was able to successfully calculate a replica count from cpu
        resource utilization (percentage of request)
      reason: ValidMetricFound
      status: 'True'
      type: ScalingActive
    - lastTransitionTime: '2024-04-12T02:09:09Z'
      message: the desired replica count is less than the minimum replica count
      reason: TooFewReplicas
      status: 'True'
      type: ScalingLimited
  currentMetrics:
    - resource:
        current:
          averageUtilization: 0
          averageValue: 2m
        name: cpu
      type: Resource
  currentReplicas: 3
  desiredReplicas: 3
  lastScaleTime: '2024-04-12T02:08:54Z'
